export const GET_CUSTOMER_SETUP_HEADER_DATA = "GET_CUSTOMER_SETUP_HEADER_DATA";
export const GET_CUSTOMER_DETAIL = "GET_CUSTOMER_DETAIL"
export const GET_CUSTOMER_SETUP_COMPONENT = "GET_CUSTOMER_SETUP_COMPONENT"